//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancelled the operation!.
        /// </summary>
        internal static string CancelledOperation {
            get {
                return ResourceManager.GetString("CancelledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access file: {0}.
        /// </summary>
        internal static string CantAccessFile {
            get {
                return ResourceManager.GetString("CantAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression rate: .
        /// </summary>
        internal static string CompressionRate {
            get {
                return ResourceManager.GetString("CompressionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have permissions to access: {0}.
        /// </summary>
        internal static string DontHavePerm {
            get {
                return ResourceManager.GetString("DontHavePerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; is missing.
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GZipTest.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough mem: .
        /// </summary>
        internal static string NotEnoughMem {
            get {
                return ResourceManager.GetString("NotEnoughMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments.
        /// </summary>
        internal static string NotEnoughPar {
            get {
                return ResourceManager.GetString("NotEnoughPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to go another, otherwise exit.
        /// </summary>
        internal static string PressEnter {
            get {
                return ResourceManager.GetString("PressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed: .
        /// </summary>
        internal static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to compress: gziptest.exe compress [file to compress] [archive name].
        /// </summary>
        internal static string ToCompress {
            get {
                return ResourceManager.GetString("ToCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to decompress: gziptest.exe decompress [archive name] [decompressed name].
        /// </summary>
        internal static string ToDecompress {
            get {
                return ResourceManager.GetString("ToDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong argument: .
        /// </summary>
        internal static string WrongArg {
            get {
                return ResourceManager.GetString("WrongArg", resourceCulture);
            }
        }
    }
}
